import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { Button, InputGroup, FormControl, Form  } from 'react-bootstrap'


export default function Mint({wallet, xcubeTokenContract, web3}) {
  const [nftPrice, setNftPrice] = useState(0);
  const [tokenURI, setTokenURI] = useState('');
  const [category, setCategory] = useState('');
  const [subject, setSubject] = useState('');
  const [totalAmount, setTotalAmount] = useState(0);
  const [tokenId, setTokenId] = useState('');


  const onClickMint = async () => {
    try {
      if (!wallet) return;
      if (!xcubeTokenContract) return;
      if (nftPrice <= 0 || tokenURI === '' || totalAmount <= 0) {
        alert('input price and tokenURI')
        return;
      }

      console.log(tokenURI + ' / ' + web3.utils.toWei(nftPrice, "milliether"))

      const response = await xcubeTokenContract.methods
        .mintNFT(tokenURI, category, subject, totalAmount)
        .send({ from : wallet, value : web3.utils.toWei(nftPrice, "milliether") });
      
      if (response.status) {
        console.log(response)
        
        //alert('success mint : ' + tokenId)
      }

      
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Form.Label htmlFor="basic-url">enter tokenURI</Form.Label>
      <InputGroup className="mb-3">
        <InputGroup.Text id="basic-addon3">
          ipfs://QmdTG3ZZxZEnCAswaAYjM4tMEsPCjWdc9917NdNjVfuY5e
        </InputGroup.Text>
        <FormControl id="basic-url" aria-describedby="basic-addon3" value={tokenURI} onChange={e => setTokenURI(e.target.value)} />
      </InputGroup>
      <InputGroup className="mb-3">
        <InputGroup.Text>category</InputGroup.Text>
        <FormControl aria-label="category" value={category} onChange={e => setCategory(e.target.value)}/>
      </InputGroup>
      <InputGroup className="mb-3">
        <InputGroup.Text>subject</InputGroup.Text>
        <FormControl aria-label="subject" value={subject} onChange={e => setSubject(e.target.value)}/>
      </InputGroup>
      <InputGroup className="mb-3">
        <InputGroup.Text>totalAmount</InputGroup.Text>
        <FormControl aria-label="totalAmount" value={totalAmount} onChange={e => setTotalAmount(e.target.value)}/>
      </InputGroup>
      <InputGroup className="mb-3">
        <InputGroup.Text>milliether</InputGroup.Text>
        <FormControl aria-label="Amount (to the nearest Ether)" value={nftPrice} onChange={e => setNftPrice(e.target.value)}/>
      </InputGroup>
        <Button onClick={() => onClickMint()}>mint</Button>
      </main>
    </div>
  )
}
